#include <stdlib.h>
#include "puttyalt_sshexport.h"
#include <string.h>
#include <stdio.h>

int sshexport_single(SSHConfigEntry *entry, char *buf, int buflen)
{
    int n = 0;
    n += snprintf(buf + n, buflen - n, "Host %s\n", entry->host_alias);
    n += snprintf(buf + n, buflen - n, "    HostName %s\n", entry->hostname);
    if (entry->port && entry->port != 22)
        n += snprintf(buf + n, buflen - n, "    Port %d\n", entry->port);
    if (entry->user[0])
        n += snprintf(buf + n, buflen - n, "    User %s\n", entry->user);
    if (entry->identity_file[0])
        n += snprintf(buf + n, buflen - n, "    IdentityFile %s\n", entry->identity_file);
    if (entry->proxy_jump[0])
        n += snprintf(buf + n, buflen - n, "    ProxyJump %s\n", entry->proxy_jump);
    if (entry->forward_agent)
        n += snprintf(buf + n, buflen - n, "    ForwardAgent yes\n");
    if (entry->forward_x11)
        n += snprintf(buf + n, buflen - n, "    ForwardX11 yes\n");
    if (entry->compression)
        n += snprintf(buf + n, buflen - n, "    Compression yes\n");
    if (entry->keepalive > 0)
        n += snprintf(buf + n, buflen - n, "    ServerAliveInterval %d\n", entry->keepalive);
    n += snprintf(buf + n, buflen - n, "\n");
    return n;
}

int sshexport_all(SSHConfigEntry *entries, int count, const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f) return -1;
    fprintf(f, "# Generated by PuttyAlt\n# https://github.com/chillymasterio/puttyalt\n\n");
    char buf[2048];
    for (int i = 0; i < count; i++) {
        sshexport_single(&entries[i], buf, sizeof(buf));
        fputs(buf, f);
    }
    fclose(f);
    return 0;
}

int sshexport_import_line(const char *line, SSHConfigEntry *entry)
{
    if (!line) return -1;
    char key[64], val[512];
    if (sscanf(line, " %63s %511[^\n]", key, val) < 2) return -1;
    if (strcmp(key, "Host") == 0) snprintf(entry->host_alias, sizeof(entry->host_alias), "%s", val);
    else if (strcmp(key, "HostName") == 0) snprintf(entry->hostname, sizeof(entry->hostname), "%s", val);
    else if (strcmp(key, "Port") == 0) entry->port = atoi(val);
    else if (strcmp(key, "User") == 0) snprintf(entry->user, sizeof(entry->user), "%s", val);
    else if (strcmp(key, "IdentityFile") == 0) snprintf(entry->identity_file, sizeof(entry->identity_file), "%s", val);
    else if (strcmp(key, "ProxyJump") == 0) snprintf(entry->proxy_jump, sizeof(entry->proxy_jump), "%s", val);
    else if (strcmp(key, "ForwardAgent") == 0) entry->forward_agent = (strcmp(val, "yes") == 0);
    else if (strcmp(key, "ForwardX11") == 0) entry->forward_x11 = (strcmp(val, "yes") == 0);
    else return 0;
    return 1;
}
