blank_issues_enabled: true
contact_links:
  - name: PuTTY Upstream Bug
    url: https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/
    about: If this is a bug in core PuTTY (not PuttyAlt-specific), report upstream
