#include "puttyalt_sshconfig.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

int sshconfig_parse(SSHConfigParser *p, const char *path)
{
    FILE *f;
    char line[1024];
    memset(p, 0, sizeof(*p));
    snprintf(p->config_path, sizeof(p->config_path), "%s", path);
    f = fopen(path, "r");
    if (!f) return -1;

    SSHHostConfig *cur = NULL;
    while (fgets(line, sizeof(line), f)) {
        size_t len = strlen(line);
        while (len > 0 && (line[len-1] == '\n' || line[len-1] == '\r'))
            line[--len] = '\0';

        /* Skip comments and empty lines */
        char *s = line;
        while (*s == ' ' || *s == '\t') s++;
        if (*s == '#' || *s == '\0') continue;

        /* Find key and value */
        char *space = strchr(s, ' ');
        if (!space) space = strchr(s, '\t');
        if (!space) continue;
        *space = '\0';
        char *val = space + 1;
        while (*val == ' ' || *val == '\t') val++;

        if (strcasecmp(s, "Host") == 0) {
            if (p->count >= SSHCFG_MAX_HOSTS) break;
            cur = &p->hosts[p->count++];
            memset(cur, 0, sizeof(*cur));
            cur->port = 22;
            snprintf(cur->alias, sizeof(cur->alias), "%s", val);
        } else if (cur) {
            if (strcasecmp(s, "HostName") == 0)
                snprintf(cur->hostname, sizeof(cur->hostname), "%s", val);
            else if (strcasecmp(s, "User") == 0)
                snprintf(cur->user, sizeof(cur->user), "%s", val);
            else if (strcasecmp(s, "Port") == 0)
                cur->port = atoi(val);
            else if (strcasecmp(s, "IdentityFile") == 0)
                snprintf(cur->identity_file, sizeof(cur->identity_file), "%s", val);
            else if (strcasecmp(s, "ProxyCommand") == 0)
                snprintf(cur->proxy_command, sizeof(cur->proxy_command), "%s", val);
            else if (strcasecmp(s, "ForwardAgent") == 0)
                cur->forward_agent = (strcasecmp(val, "yes") == 0);
            else if (strcasecmp(s, "Compression") == 0)
                cur->compression = (strcasecmp(val, "yes") == 0);
            else if (strcasecmp(s, "LocalForward") == 0)
                snprintf(cur->local_forward, sizeof(cur->local_forward), "%s", val);
            else if (strcasecmp(s, "RemoteForward") == 0)
                snprintf(cur->remote_forward, sizeof(cur->remote_forward), "%s", val);
            else if (strcasecmp(s, "ProxyJump") == 0)
                snprintf(cur->jump_host, sizeof(cur->jump_host), "%s", val);
            else if (strcasecmp(s, "ServerAliveInterval") == 0)
                cur->server_alive_interval = atoi(val);
            else if (strcasecmp(s, "ConnectTimeout") == 0)
                cur->connection_timeout = atoi(val);
        }
    }
    fclose(f);
    return p->count;
}

int sshconfig_write(const SSHConfigParser *p, const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f) return -1;
    fprintf(f, "# Generated by PuttyAlt\n\n");
    for (int i = 0; i < p->count; i++) {
        const SSHHostConfig *h = &p->hosts[i];
        fprintf(f, "Host %s\n", h->alias);
        if (h->hostname[0]) fprintf(f, "    HostName %s\n", h->hostname);
        if (h->user[0]) fprintf(f, "    User %s\n", h->user);
        if (h->port != 22) fprintf(f, "    Port %d\n", h->port);
        if (h->identity_file[0]) fprintf(f, "    IdentityFile %s\n", h->identity_file);
        if (h->forward_agent) fprintf(f, "    ForwardAgent yes\n");
        if (h->compression) fprintf(f, "    Compression yes\n");
        if (h->jump_host[0]) fprintf(f, "    ProxyJump %s\n", h->jump_host);
        if (h->server_alive_interval) fprintf(f, "    ServerAliveInterval %d\n", h->server_alive_interval);
        if (h->connection_timeout) fprintf(f, "    ConnectTimeout %d\n", h->connection_timeout);
        fprintf(f, "\n");
    }
    fclose(f);
    return 0;
}

const SSHHostConfig *sshconfig_find(const SSHConfigParser *p, const char *alias)
{
    for (int i = 0; i < p->count; i++)
        if (strcmp(p->hosts[i].alias, alias) == 0)
            return &p->hosts[i];
    return NULL;
}

int sshconfig_add(SSHConfigParser *p, const SSHHostConfig *host)
{
    if (p->count >= SSHCFG_MAX_HOSTS) return -1;
    memcpy(&p->hosts[p->count++], host, sizeof(SSHHostConfig));
    return 0;
}

int sshconfig_remove(SSHConfigParser *p, const char *alias)
{
    for (int i = 0; i < p->count; i++) {
        if (strcmp(p->hosts[i].alias, alias) == 0) {
            for (int j = i; j < p->count - 1; j++)
                p->hosts[j] = p->hosts[j + 1];
            p->count--;
            return 0;
        }
    }
    return -1;
}
